### ISSUE TITLE
Add more rows to sample data

### ISSUE THREAD

**Issue by O-Mohammed** [The-Strategy-Unit/nhp_evidence_maps#16]
currently sample data only has 1 value for the '?' mechanism.

**Comment by O-Mohammed** [comment]
also fix bug with my_dataset error when loading app

**Comment by O-Mohammed** [comment]
reopened as evidence map is aggregating sample data and reducing number of values shown

**Comment by matt-dray** [comment]
No longer using sample data; now using real data.
