### ISSUE TITLE
Confirm license

### ISSUE THREAD

**Issue by matt-dray** [The-Strategy-Unit/nhp_evidence_maps#52]
[Currently MIT](https://github.com/The-Strategy-Unit/nhp_evidence_maps/blob/main/LICENSE.md). Are we happy with that?

Should there be a secondary license? This may need to happen because the app presents documenation. In [the GDS Way](https://gds-way.digital.cabinet-office.gov.uk/manuals/licensing.html#guidelines-for-repositories-that-are-open-documentation) this would be OGL. [The NHP project information repo](https://github.com/The-Strategy-Unit/nhp_project_information/blob/main/LICENSE.md) is a flavour of CC.

**Comment by ChrisBeeley** [comment]
Can I ask what you mean by "the app presents documenation"?

Shall we just thrash this out at standup next week?

**Comment by ChrisBeeley** [comment]
MIT licence
